<?php

declare(strict_types=1);
session_start(); header('Content-Type: application/json; charset=utf-8'); require_once __DIR__ . '/../../../config/database.php'; require_once __DIR__ . '/notification-helper.php';
$userId = (int) ($_SESSION['user_id'] ?? 0); if ($userId < 1) { http_response_code(401); echo json_encode(['error' => 'Authentification requise.']); exit; }
function getUser(PDO $pdo, int $userId): ?array { $statement = $pdo->prepare('SELECT id, role, is_active FROM users WHERE id = :id LIMIT 1'); $statement->execute(['id' => $userId]); $user = $statement->fetch(); return $user && $user['is_active'] ? $user : null; }
$user = getUser($pdo, $userId); if (!$user) { http_response_code(401); echo json_encode(['error' => 'Compte inactif.']); exit; }
$quoteId = filter_input(INPUT_GET, 'quote_id', FILTER_VALIDATE_INT);
if ($_SERVER['REQUEST_METHOD'] === 'GET') { if (!$quoteId) { http_response_code(422); echo json_encode(['error' => 'Demande de devis invalide.']); exit; } $statement = $pdo->prepare("SELECT qr.id, qr.quote_id, qr.artisan_id, qr.proposed_amount, qr.estimated_days, qr.message, qr.status, qr.created_at, CONCAT(u.first_name, ' ', u.last_name) AS artisan_name FROM quote_responses qr INNER JOIN artisan_profiles ap ON ap.id = qr.artisan_id INNER JOIN users u ON u.id = ap.user_id INNER JOIN quotes q ON q.id = qr.quote_id WHERE qr.quote_id = :quote_id AND (q.client_id = :user_id OR ap.user_id = :user_id) ORDER BY qr.created_at DESC"); $statement->execute(['quote_id' => $quoteId, 'user_id' => $userId]); echo json_encode(['success' => true, 'data' => $statement->fetchAll()]); exit; }
if ($_SERVER['REQUEST_METHOD'] !== 'POST') { http_response_code(405); header('Allow: GET, POST'); echo json_encode(['error' => 'Méthode non autorisée.']); exit; }
$input = json_decode(file_get_contents('php://input'), true); if (!is_array($input)) { http_response_code(400); echo json_encode(['error' => 'Données JSON invalides.']); exit; } $action = $input['action'] ?? 'respond';
if ($action === 'respond') { if ($user['role'] !== 'artisan') { http_response_code(403); echo json_encode(['error' => 'Seuls les artisans peuvent répondre.']); exit; } $quoteId = filter_var($input['quoteId'] ?? null, FILTER_VALIDATE_INT); $amount = filter_var($input['proposedAmount'] ?? null, FILTER_VALIDATE_FLOAT); $days = filter_var($input['estimatedDays'] ?? null, FILTER_VALIDATE_INT); $message = trim((string) ($input['message'] ?? '')); if (!$quoteId || $amount === false || $amount <= 0 || $days === false || $days < 1 || $message === '') { http_response_code(422); echo json_encode(['error' => 'Proposition invalide.']); exit; } try { $artisan = $pdo->prepare("SELECT ap.id FROM artisan_profiles ap WHERE ap.user_id = :user_id AND ap.verification_status = 'verified'"); $artisan->execute(['user_id' => $userId]); $artisanId = (int) $artisan->fetchColumn(); if (!$artisanId) { http_response_code(403); echo json_encode(['error' => 'Profil artisan non vérifié.']); exit; } $quote = $pdo->prepare("SELECT id FROM quotes WHERE id = :id AND quote_type = 'tender' AND status = 'open'"); $quote->execute(['id' => $quoteId]); if (!$quote->fetch()) { http_response_code(404); echo json_encode(['error' => 'Appel d’offres introuvable.']); exit; } $statement = $pdo->prepare("INSERT INTO quote_responses (quote_id, artisan_id, proposed_amount, estimated_days, message) VALUES (:quote_id, :artisan_id, :amount, :days, :message) ON DUPLICATE KEY UPDATE proposed_amount = VALUES(proposed_amount), estimated_days = VALUES(estimated_days), message = VALUES(message), status = 'pending'"); $statement->execute(['quote_id' => $quoteId, 'artisan_id' => $artisanId, 'amount' => $amount, 'days' => $days, 'message' => $message]); echo json_encode(['success' => true, 'message' => 'Proposition envoyée.']); } catch (PDOException $exception) { http_response_code(500); echo json_encode(['error' => 'Impossible d’envoyer la proposition.']); } exit; }
if ($action === 'accept') { if ($user['role'] !== 'client') { http_response_code(403); echo json_encode(['error' => 'Seul le client peut accepter une proposition.']); exit; } $responseId = filter_var($input['responseId'] ?? null, FILTER_VALIDATE_INT); if (!$responseId) { http_response_code(422); echo json_encode(['error' => 'Proposition invalide.']); exit; } try { $pdo->beginTransaction(); $statement = $pdo->prepare("SELECT qr.*, q.client_id, q.title, q.description, q.project_address, q.deadline, q.id AS quote_id FROM quote_responses qr INNER JOIN quotes q ON q.id = qr.quote_id WHERE qr.id = :id AND q.client_id = :client_id AND q.status = 'open' AND qr.status = 'pending' FOR UPDATE"); $statement->execute(['id' => $responseId, 'client_id' => $userId]); $response = $statement->fetch(); if (!$response) { $pdo->rollBack(); http_response_code(404); echo json_encode(['error' => 'Proposition indisponible.']); exit; } $order = $pdo->prepare("INSERT INTO orders (client_id, artisan_id, quote_id, title, description, amount, delivery_address, expected_date) VALUES (:client_id, :artisan_id, :quote_id, :title, :description, :amount, :address, :expected_date)"); $order->execute(['client_id' => $userId, 'artisan_id' => $response['artisan_id'], 'quote_id' => $response['quote_id'], 'title' => $response['title'], 'description' => $response['description'], 'amount' => $response['proposed_amount'], 'address' => $response['project_address'], 'expected_date' => $response['deadline']]); $pdo->prepare("UPDATE quote_responses SET status = 'accepted' WHERE id = :id")->execute(['id' => $responseId]); $pdo->prepare("UPDATE quote_responses SET status = 'rejected' WHERE quote_id = :quote_id AND id <> :id AND status = 'pending'")->execute(['quote_id' => $response['quote_id'], 'id' => $responseId]); $pdo->prepare("UPDATE quotes SET status = 'accepted' WHERE id = :id")->execute(['id' => $response['quote_id']]); $pdo->commit(); echo json_encode(['success' => true, 'message' => 'Proposition acceptée. Commande créée.']); } catch (Throwable $exception) { if ($pdo->inTransaction()) $pdo->rollBack(); http_response_code(500); echo json_encode(['error' => 'Impossible de créer la commande.']); } exit; }
http_response_code(422); echo json_encode(['error' => 'Action inconnue.']);
